services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    image: your-backend-image:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./config/jwt:/app/config/jwt:ro # Mounts local JWT keys as read-only
    environment:
      - JWT_PASSPHRASE=${JWT_PASSPHRASE} # Pass passphrase via environment variable
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: logistics
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"