doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'            # Default is 'version'
            version_column_length: 1024               # Default is 1024
            executed_at_column_name: 'executed_at'    # Default is 'executed_at'
            execution_time_column_name: 'execution_time' # Default is 'execution_time'
    enable_profiler: false